<?php

namespace AppBundle\Repository;

/**
 * AnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllChecked($answers)
    {
        return $allChecked = $this->createQueryBuilder('a')
            ->select('a')
            ->where('a.id IN (:ids)')
            ->setParameter('ids', $answers)
            ->distinct(true)
            ->getQuery()
            ->getResult();
    }
}
