<?php

namespace AppBundle\Repository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSpecificQuestions($options)
    {
        $questions = [];

        foreach ($options['books'] as $book)
        {
            $totalRows = $this->createQueryBuilder('q')
                ->select('q.id')
                ->where('q.book = :book')
                ->setParameter('book', $book)
                ->distinct(true)
                ->getQuery()
                ->getResult();

            shuffle($totalRows);
            array_splice($totalRows, $options['amount']);

            $results = $this->createQueryBuilder('q')
                ->select('q')
                ->where('q.id IN (:ids)')
                ->setParameter('ids', $totalRows)
                ->setMaxResults($options['amount'])
                ->distinct(true)
                ->getQuery()
                ->getResult();
            array_push($questions, $results);
        }
        return $questions;
    }
}
