<?php

namespace AppBundle\Repository;

/**
 * QuestionReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionReportRepository extends \Doctrine\ORM\EntityRepository
{
}
