<?php

namespace AppBundle\Repository;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRepository extends \Doctrine\ORM\EntityRepository
{
    public function bestResultsFromEachCategory($userId, $category, $limit = false)
    {
        $qb = $this->createQueryBuilder('t')
            ->select('t')
            ->where('t.userId = :userId')
            ->andWhere('t.category = :category')
            ->setParameter('userId', $userId)
            ->setParameter('category', $category)
            ->addOrderBy('t.correct', 'desc')
            ->addOrderBy('t.timeSpent', 'asc');
            $limit ? $qb = $qb->setMaxResults($limit)->getQuery() : $qb = $qb->getQuery();

        return $qb->getResult();
    }
}
